import type { Campaign, Donation, CampaignHighlight } from "./types";

export const mockCampaigns: Campaign[] = [
  { id: "campaign-1", slug: "science-lab-modernization", image: "/campaigns/science.jpg", status: "ACTIVE", faculty: "B.Ed Science", title: "Science Lab Modernization", description: "Upgrading our biology and chemistry laboratories with modern equipment and improved learning facilities.", detailedDescription: "The Science Lab Modernization campaign aims to improve the learning environment for students studying science.", whyMatters: "Modern laboratory facilities allow students to gain practical experience and develop skills required for future scientific careers.", category: "Science", isHighlight: true, raised: 185000, goal: 250000, createdAt: "2026-01-10T00:00:00.000Z" },
  { id: "campaign-2", slug: "merit-scholarship-fund-2026", image: "/campaigns/merit-scholarship.jpg", status: "ACTIVE", faculty: "BBA", title: "Merit Scholarship Fund 2026", description: "Supporting talented students from financially disadvantaged backgrounds by helping cover their educational expenses.", whyMatters: "Supporting deserving students makes quality education more accessible.", category: "Scholarship", isHighlight: true, raised: 240000, goal: 320000, createdAt: "2026-01-08T00:00:00.000Z" },
  { id: "campaign-3", slug: "campus-sports-complex", image: "/campaigns/sports.jpg", status: "ACTIVE", faculty: "BA", title: "Campus Sports Complex", description: "Building a multipurpose sports facility to encourage physical activity, teamwork and student well-being.", category: "Sports", isHighlight: false, raised: 310000, goal: 420000, createdAt: "2026-01-05T00:00:00.000Z" },
  { id: "campaign-4", slug: "library-digitization-phase-2", image: "/campaigns/library.jpg", status: "UPCOMING", faculty: "BICTE", title: "Library Digitization — Phase 2", description: "Expanding our digital archive with academic resources, manuscripts and regional research collections.", category: "Library", isHighlight: false, raised: 0, goal: 180000, launchDate: "Ashoj 2083", createdAt: "2026-01-03T00:00:00.000Z" },
  { id: "campaign-5", slug: "smart-learning-environment", image: "/campaigns/smart.jpg", status: "UPCOMING", faculty: "B.Ed Math", title: "Smart Learning Environment", description: "Expanding smart learning facilities to create a more interactive and technology-friendly classroom environment.", category: "Technology", isHighlight: false, raised: 0, goal: 220000, launchDate: "Kartik 2083", createdAt: "2026-01-02T00:00:00.000Z" },
  { id: "campaign-6", slug: "campus-development-initiative", image: "/campaigns/campaign.jpg", status: "UPCOMING", faculty: "BA", title: "Campus Development Initiative", description: "Supporting future campus improvements and creating a better environment for students and faculty.", category: "Campus Development", isHighlight: false, raised: 0, goal: 400000, launchDate: "Baisakh 2084", createdAt: "2026-01-01T00:00:00.000Z" },
  { id: "campaign-7", slug: "smart-classroom-upgrade", image: "/campaigns/smart.jpg", status: "COMPLETED", faculty: "B.Ed Math", title: "Smart Classroom Upgrade", description: "Successfully installed interactive smart boards and projectors across the campus.", category: "Technology", isHighlight: false, raised: 210000, goal: 210000, createdAt: "2025-11-20T00:00:00.000Z" },
  { id: "campaign-8", slug: "digital-library-expansion", image: "/campaigns/library.jpg", status: "COMPLETED", faculty: "BICTE", title: "Digital Library Expansion", description: "Expanded access to digital subscriptions, journals and academic research materials.", category: "Library", isHighlight: false, raised: 150000, goal: 150000, createdAt: "2025-11-10T00:00:00.000Z" },
  { id: "campaign-9", slug: "sports-development-program", image: "/campaigns/sports.jpg", status: "COMPLETED", faculty: "BA", title: "Sports Development Program", description: "Successfully supported student participation in sports and extracurricular activities.", category: "Sports", isHighlight: false, raised: 180000, goal: 180000, createdAt: "2025-11-01T00:00:00.000Z" },
];

export const mockDonations: Donation[] = [];

export const mockHighlights: CampaignHighlight[] = [];